#!/usr/bin/env bash

if [ $# -ne 2 ]; then
  echo "USAGE: $0 <namespace> <name>"
  exit 1
fi

oc get namespace $1 &>/dev/null
if [ $? -ne 0 ]; then
  read -s -p "Namespace $1 doesn't exist. Create it? [Y/n] " RESPONSE
  if [ -z "${RESPONSE}" ] || [ "${RESPONSE}" == "y" ]; then
    echo
    oc create namespace $1
  else
    echo "Ok. Stopped."
    exit 1
  fi
fi

oc label namespace $1 claimed="$2" || { exit 1; }
