#!/usr/bin/env bash

usage(){
  echo "USAGE: $0 <namespace> <image tag> <my name> [--force|-f] [--gpus|-g <count>]"
}

# script-kiddied from https://medium.com/@Drew_Stokes/bash-argument-parsing-54f3b81a6a8f
PARAMS=""
FORCE=""
while (( "$#" )); do
  case "$1" in
    -f|--force)
      FORCE=" --force "
      shift
      ;;
		-g|--gpus)
      if [ ! -n "$2" ] || [ ${2:0:1} == "-" ]; then
        echo "Error: Argument for $1 is missing" >&2
        usage
        exit 1
      fi
      test -z "${2//[^0-9]}"
      if [ $? -eq 0 ]; then
        echo "Error: Argument for $1 is not a number. Got '$2'" >&2
        usage
        exit 1
      fi
      GPUS=$2
      shift 2
      ;;
    -*|--*=) # unsupported flags
      echo "Error: Unsupported flag $1" >&2
      usage
      exit 1
      ;;
    *) # preserve positional arguments
      PARAMS="$PARAMS $1"
      shift
      ;;
  esac
done
# set positional arguments in their proper place
eval set -- "$PARAMS"

if [ $# -ne 3 ]; then
  echo "USAGE: $0 <namespace> <image tag> <my name> [--force|-f]"
  usage
  exit 1
fi

NAMESPACE=$1
TAG=$2
NAME=$3
WITH_DATE=$(date "+${NAME}-%Y%m%M")

SED_STR="s+REPLACE_NAMESPACE+${NAMESPACE}+g; s+REPLACE_TAG+${TAG}+g"

# Set things up for deploying GPUs
if [ "$GPUS" == "1" ]; then
  if [ -z "${PL_LICENSE_NAME}" ] || [ -z "${PL_LICENSE_VALUE}" ]; then
    echo "PL_LICENSE_NAME and/or PL_LICENSE_VALUE aren't set in your environment. GPU's won't be enabled without them"
    exit 1
  fi
	SED_STR="${SED_STR}; s+REPLACE_LICENSE_NAME+${PL_LICENSE_NAME}+g; s+REPLACE_LICENSE_VALUE+${PL_LICENSE_VALUE}+g; s+REPLACE_GPUS+${GPUS}+g"
fi

# verify the cluster
CTXT=$(oc config current-context | cut -d/ -f2)
read -s -p "Deploying to ${CTXT}. Ok? [Y/n] " RESPONSE
echo
if [ "${RESPONSE}" == "n" ]; then exit 0; fi

# claim the namespace

DIR=$(dirname $0)

${DIR}/claim ${FORCE} "${NAMESPACE}" "${WITH_DATE}" || { exit 1; }

sed "${SED_STR}" ${DIR}/global.yaml | oc apply -f - || { exit 1; }

# if it doesn't already exist, then make the pull secret
oc get secrets -n ${NAMESPACE} pl-pull &>/dev/null
if [ $? -ne 0 ]; then
  if [ -z "${PERCEPTILABS_AZURECR_PWD}" ]; then
    echo "The required PERCEPTILABS_AZURECR_PWD environment variable isn't set."
    exit 1
  fi

  # you can't update a secret idempotently with oc create secret. Just delete and recreate.
  oc delete secret pl-pull --namespace ${NAMESPACE} --ignore-not-found
  oc create secret docker-registry pl-pull \
    --docker-server=perceptilabs.azurecr.io \
    --docker-username=perceptilabs \
    --docker-password=${PERCEPTILABS_AZURECR_PWD} \
    --namespace ${NAMESPACE} || { exit 1; }
fi

if [ -z "$GPUS" ]; then
	sed "${SED_STR}" ${DIR}/namespaced.yaml | oc apply --validate=false -n ${NAMESPACE} -f - || { exit 1; }
elif [ "$GPUS" == "1" ]; then
  if [ -z "${PL_LICENSE_NAME}" ] || [ -z "${PL_LICENSE_VALUE}" ]; then
    echo "PL_LICENSE_NAME and/or PL_LICENSE_VALUE aren't set in your environment. GPU's won't be enabled without them"
    exit 1
  fi
	SED_STR="${SED_STR}; s+REPLACE_LICENSE_NAME+${PL_LICENSE_NAME}+g; s+REPLACE_LICENSE_VALUE+${PL_LICENSE_VALUE}+g; s+REPLACE_GPUS+${GPUS}+g"
	sed "${SED_STR}" ${DIR}/gpu.yaml | oc apply --validate=false -n ${NAMESPACE} -f - || { exit 1; }
fi
url=$(oc get routes.route.openshift.io --namespace ${NAMESPACE} perceptilabs-frontend --output="custom-columns=url:spec.host" --no-headers)
echo "Serving at ${url}"
