#!/usr/bin/env bash

if [ $# -ne 1 ]; then
  echo USAGE: $0 url version
  exit 1
fi

APP_URL=$1
RC=$(curl -s -o /dev/null -w "%{http_code}" --head ${APP_URL})
if [ "${RC}" == "403" ]; then
  echo "Application repo is not authorized at ${APP_URL}"
  echo "Is the repository public?"
  exit 1
elif [ "${RC}" != "200" ]; then
  echo "Application repo is not available at ${APP_URL}. HTTP code: ${RC}"
  exit 1
fi
