kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: perceptilabs-example-sc
  annotations:
    description: Example Storage for PerceptiLabs
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Delete
volumeBindingMode: Immediate
