kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: perceptilabs-example-sc
  annotations:
    description: Example Storage for PerceptiLabs
provisioner: kubernetes.io/aws-ebs
parameters:
  fsType: ext4
  type: gp2
reclaimPolicy: Delete
volumeBindingMode: Immediate
