apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: REPLACE_NAMESPACE-operatorgroup
  namespace: REPLACE_NAMESPACE
spec:
  serviceAccountName: perceptilabs-operator
  targetNamespaces:
  - REPLACE_NAMESPACE
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: REPLACE_SUBSCRIPTION_NAME
  namespace: REPLACE_NAMESPACE
spec:
  channel: stable
  name: REPLACE_REPO_NAME
  source: perceptilabs-operators
  sourceNamespace: openshift-marketplace
  namespace: REPLACE_NAMESPACE
